### ISSUE TITLE
lots of written lesson contents

### ISSUE THREAD

**Issue by libaice** [Cyfrin/assembly-evm-opcodes-and-formal-verification-course#10]
<img width="1056" alt="Screenshot 2024-04-15 at 13 11 36" src="https://github.com/Cyfrin/assembly-evm-opcodes-and-formal-verification-course/assets/48044642/19f400a2-4a09-4b32-8512-414ab3ff63b5">

ref: https://github.com/Cyfrin/Updraft/blob/647ef10ef4b50490bba33ac5ec776937c74a8b9c/courses/formal-verification/1-horse-store/40-updating-tests-to-fuzz-tests/%2Bpage.md

**Comment by PatrickAlphaC** [comment]
We are tracking this internally, thanks!

**Comment by PatrickAlphaC** [comment]
Closing, this should be fixed now.

**Comment by PatrickAlphaC** [comment]
Ok this should actually be fixed!
