### ISSUE TITLE
Incorrect video lesson content of part 19 in section 2

### ISSUE THREAD

**Issue by PitrikYan** [Cyfrin/assembly-evm-opcodes-and-formal-verification-course#4]
On Cyfrin updraft, in the "Horse store" section, the content of part 19 (Opcode EQ) is the same like the previous part (Dispatching). The issue is just with video lesson, written leason seems to be ok. Hope here is the correct place to inform about this :) Thx

**Comment by cromewar** [comment]
Hello @PitrikYan thanks a lot for letting us know this, we will check and correct as soon as possible.

**Comment by PatrickAlphaC** [comment]
This should be resolved, closing!
