### ISSUE TITLE
Error in HorseStore Lesson 43 

### ISSUE THREAD

**Issue by mcgrathcoutinho** [Cyfrin/assembly-evm-opcodes-and-formal-verification-course#6]
Hi,

The lesson 43 video in the HorseStore module at timestamp 7:00 incorrectly mentions the next free memory pointer to be 0x6a. The correct value should be 0xa0 since that is the hex representation of 128 + 32 (160).

To quickly confirm this just use: `cast to-base 160 hex` in foundry

**Comment by cromewar** [comment]
Thanks for this, we posted and update on the platform.
