### ISSUE TITLE
All image respources are broken

### ISSUE THREAD

**Issue by libaice** [Cyfrin/assembly-evm-opcodes-and-formal-verification-course#9]
for example :
[https://updraft.cyfrin.io/formal-verification-1/11-push-and-add-opcodes/push-and-add-opcodes-1.png](https://updraft.cyfrin.io/formal-verification-1/11-push-and-add-opcodes/push-and-add-opcodes-1.png)

![Screenshot 2024-04-13 at 19 35 15](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/0d4db39c-0e2b-4b2a-96e8-f03d4043dbc2/deff3ab9-d367-4697-b331-199f5a8ac126?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My8wZDRkYjM5Yy0wZTJiLTRiMmEtOTZlOC1mMDNkNDA0M2RiYzIvZGVmZjNhYjktZDM2Ny00Njk3LWIzMzEtMTk5ZjVhOGFjMTI2IiwiaWF0IjoxNzEzMjgzNDU3LCJleHAiOjMzMjgzODQzNDU3fQ.ubRmcGZcUb6dhOfQHhys74gCbCNMAvvspDoBF_gx5AU "=1134x")

![Screenshot 2024-04-13 at 19 36 35](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/f2333f19-a26b-4a34-838c-4955c6117591/7bb2fe84-d70e-4da5-8c5a-4d3acfdf9735?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My9mMjMzM2YxOS1hMjZiLTRhMzQtODM4Yy00OTU1YzYxMTc1OTEvN2JiMmZlODQtZDcwZS00ZGE1LThjNWEtNGQzYWNmZGY5NzM1IiwiaWF0IjoxNzEzMjgzNDU3LCJleHAiOjMzMjgzODQzNDU3fQ.grU92cx-TVvDvecdYbRn7Jak1ov1vtQzim--YJ2B1GY "=1056x")

**Comment by EngrPips** [comment]
Hello @libaice , please confirm if this is still an issue for you. someone reported something similar on discord and the situation was fixed i believe.
